apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"synergychat-api"},"name":"synergychat-api","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"synergychat-api"}},"template":{"metadata":{"labels":{"app":"synergychat-api"}},"spec":{"containers":[{"image":"bootdotdev/synergychat-api:latest","name":"synergychat-api"}]}}}}
  creationTimestamp: "2024-08-12T19:59:45Z"
  generation: 1
  labels:
    app: synergychat-api
  name: synergychat-api
  namespace: default
  resourceVersion: "7850"
  uid: 2113f736-00c8-4f30-8a00-42c0b2de0858
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synergychat-api
    spec:
      containers:
      - image: bootdotdev/synergychat-api:latest
        imagePullPolicy: Always
        name: synergychat-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-08-12T19:59:45Z"
    lastUpdateTime: "2024-08-12T19:59:45Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-08-12T20:09:45Z"
    lastUpdateTime: "2024-08-12T20:09:45Z"
    message: ReplicaSet "synergychat-api-67554b788b" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
